title:  Correctional Redemption
description: >
  Hints, tips, code samples, observations, and loosely related tidbits from a
  devoted student of criminology, corrections, and crime analysis.

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://blueogive.github.io/

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
  - title: 'Favorites'
    url: '#'
    submenu:
      - title: 'Code Highlighter'
        url: '/intro/code-highlighting-post/'
      - title: 'Sample Post'
        url: '/intro/sample-post/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'

# Owner/author information
owner:
  name:           Mark Coggeshall
  site:           https://blueogive.github.io
  avatar:         images/coggeshallm_formal_small.png
  bio: >
    "Criminologist, student of the correctional process, and admirer of the
    open source software community. All opinions and errors are my own."
  email:          mark.coggeshall@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: MarkCoggeshall # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: blueogive

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/blueogive"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/mark-coggeshall-4272676/"
  # - title: "youtube"
  #   url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background: "linen_fabric_background_04_hd_picture_169825.jpg"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", ".vscode"]
plugins: [jekyll-paginate]
# theme: neo-hpstr-jekyll-theme
# theme: jekyll-theme-leap-day
theme: jekyll-theme-midnight
